services:
  - type: web
    name: gestion-guardavidas
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      touch database/database.sqlite
      php artisan key:generate
      npm install
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true